FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY riploy/riploy.go ./
COPY riploy/riploy_catalogo.csv ./

RUN go build -o riploy riploy.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app

COPY --from=builder /app/riploy ./
COPY --from=builder /app/riploy_catalogo.csv ./

CMD ["./riploy"]