FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY consumidor2 ./
RUN go build -o consumidor2 .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/consumidor2 .
CMD ["./consumidor2"]