FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY proto ./proto
COPY consumidor3 ./
RUN go build -o consumidor3 .

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/consumidor3 .
CMD ["./consumidor3"]